#![allow(missing_docs)]
//! Compliance test harness: runs each YAML Test Suite case through both
//! the C harness and the Rust scanner/parser, then compares the outputs.
//!
//! Uses `datatest-stable` for file-driven test generation.
//!
//! When `target/c-baseline-tokens.json` and `target/c-baseline-events.json`
//! exist (generated by `just c-baseline`), the C subprocess is NOT spawned —
//! results come from the cache. This eliminates ~700 process spawns per run.
//!
//! Two test functions are registered:
//! - `compliance_test`: token-level comparison via scanner
//! - `event_compliance_test`: event-level comparison via parser

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use yamalgam_compare::c_baseline::{self, CacheEntry};
use yamalgam_compare::{
    CompareEventResult, CompareResult, compare_events_cached, compare_input_cached,
};

/// Find the workspace root by walking up from CARGO_MANIFEST_DIR.
fn workspace_root() -> PathBuf {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".to_string()));
    let mut dir = manifest_dir.as_path();
    loop {
        if dir.join("Cargo.lock").exists() {
            return dir.to_path_buf();
        }
        dir = match dir.parent() {
            Some(p) => p,
            None => return manifest_dir,
        };
    }
}

/// Lazily loaded token baseline cache.
fn token_cache() -> &'static Option<HashMap<String, CacheEntry>> {
    static CACHE: OnceLock<Option<HashMap<String, CacheEntry>>> = OnceLock::new();
    CACHE.get_or_init(|| {
        let path = workspace_root().join("target/c-baseline-tokens.json");
        c_baseline::load(&path)
    })
}

/// Lazily loaded event baseline cache.
fn event_cache() -> &'static Option<HashMap<String, CacheEntry>> {
    static CACHE: OnceLock<Option<HashMap<String, CacheEntry>>> = OnceLock::new();
    CACHE.get_or_init(|| {
        let path = workspace_root().join("target/c-baseline-events.json");
        c_baseline::load(&path)
    })
}

/// Extract the test ID from a test suite file path (e.g., "2AUY" from "2AUY.yaml").
fn test_id(path: &Path) -> String {
    path.file_stem().unwrap().to_string_lossy().to_string()
}

fn compliance_test(path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let content = std::fs::read_to_string(path)?;
    let id = test_id(path);

    let yaml_input = match c_baseline::extract_yaml_input(&content) {
        Some(input) => input,
        None => {
            eprintln!("SKIP: no yaml input found in {}", path.display());
            return Ok(());
        }
    };

    // Use cached C result if available, otherwise fall back to subprocess.
    let cached = token_cache().as_ref().and_then(|cache| cache.get(&id));

    let result = compare_input_cached(cached, yaml_input.as_bytes());

    match &result {
        CompareResult::Match { token_count } => {
            eprintln!("PASS: {id} ({token_count} tokens matched)");
        }
        CompareResult::CSuccessRustError {
            rust_error,
            c_token_count,
        } => {
            eprintln!("EXPECTED: {id} (C produced {c_token_count} tokens, Rust: {rust_error})");
        }
        CompareResult::BothErrorMatch => {
            eprintln!("PASS: {id} (both errored, matching)");
        }
        CompareResult::BothErrorMismatch { .. } => {
            eprintln!("PASS: {id} (both errored)");
        }
        CompareResult::RustSuccessCError {
            c_error,
            rust_token_count,
        } => {
            eprintln!("UNEXPECTED: {id} (Rust produced {rust_token_count} tokens, C: {c_error})");
        }
        CompareResult::TokenMismatch {
            index,
            c_token,
            rust_token,
            ..
        } => {
            eprintln!(
                "MISMATCH: {id} at index {index} (C: {:?}, Rust: {:?})",
                c_token.kind, rust_token.kind
            );
        }
    }

    Ok(())
}

fn event_compliance_test(path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let content = std::fs::read_to_string(path)?;
    let id = test_id(path);

    let yaml_input = match c_baseline::extract_yaml_input(&content) {
        Some(input) => input,
        None => {
            eprintln!("EVENT_SKIP: no yaml input found in {}", path.display());
            return Ok(());
        }
    };

    // Use cached C result if available, otherwise fall back to subprocess.
    let cached = event_cache().as_ref().and_then(|cache| cache.get(&id));

    let result = compare_events_cached(cached, yaml_input.as_bytes());

    match &result {
        CompareEventResult::Match { event_count } => {
            eprintln!("EVENT_PASS: {id} ({event_count} events matched)");
        }
        CompareEventResult::CSuccessRustError {
            rust_error,
            c_event_count,
        } => {
            eprintln!(
                "EVENT_EXPECTED: {id} (C produced {c_event_count} events, Rust: {rust_error})"
            );
        }
        CompareEventResult::BothErrorMatch => {
            eprintln!("EVENT_PASS: {id} (both errored, matching)");
        }
        CompareEventResult::BothErrorMismatch { .. } => {
            eprintln!("EVENT_PASS: {id} (both errored)");
        }
        CompareEventResult::RustSuccessCError {
            c_error,
            rust_event_count,
        } => {
            eprintln!(
                "EVENT_UNEXPECTED: {id} (Rust produced {rust_event_count} events, C: {c_error})"
            );
        }
        CompareEventResult::EventMismatch {
            index,
            c_event,
            rust_event,
            ..
        } => {
            eprintln!(
                "EVENT_MISMATCH: {id} at index {index} (C: {:?}, Rust: {:?})",
                c_event.kind, rust_event.kind
            );
        }
    }

    Ok(())
}

datatest_stable::harness! {
    { test = compliance_test, root = "../../vendor/yaml-test-suite", pattern = r"\.yaml$" },
    { test = event_compliance_test, root = "../../vendor/yaml-test-suite", pattern = r"\.yaml$" },
}
