#!/usr/bin/env bash
# Generated by claylo-rs copier template

OLD_CRATE="yamalgam"
OLD_SNAKE="yamalgam"
OLD_PASCAL="Yamalgam"

read -p "New crate name (kebab-case): " NEW_CRATE
NEW_SNAKE="${NEW_CRATE//-/_}"
NEW_PASCAL=$(perl -e '$_ = shift; s/(^|-)(\w)/\U$2/g; print' "$NEW_CRATE")

# love the smell of perl in the morning! spares us BSD/GNU sed difference headaches
find . -type f -not -path './.git/*' -exec perl -pi -e "
  s/\Q${OLD_CRATE}\E/${NEW_CRATE}/g;
  s/\Q${OLD_SNAKE}\E/${NEW_SNAKE}/g;
  s/\Q${OLD_PASCAL}\E/${NEW_PASCAL}/g;
" {} +

# rename files/dirs as needed
for f in $(find . -depth -name "*${OLD_SNAKE}*" -not -path './.git/*'); do
  mv "$f" "$(echo "$f" | perl -pe "s/\Q${OLD_SNAKE}\E/${NEW_SNAKE}/g")"
done
